name = "Minecraft Server 1 . 20 . 4 Vanilla Modpack"
author = "Nic4Las"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc8b15bad23e2068716a0115aaa5ea3ff45242cb13738d0a5702d2eda75025ba"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
